trigger:
- master
resources:
  - repo: self
pool:
  vmImage: ubuntu-latest
stages:
  - stage:
    displayName: Build
    jobs:
      - job: Build
        displayName: Build Docker image
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@0
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureContainerRegistry: 'ffffffffffff'
            action: 'Build an image'
            dockerFile: '/app/Dockerfile'
            imageName: '$(Build.Repository.Name):$(Build.BuildId)'